default:
  image: cirrusci/flutter:latest
  before_script:
    - cd counter_test
    - flutter pub get

stages:
  - test
  - lint
  - build
  - deploy

flutter_test:
  stage: test
  script:
    - flutter test

flutter_lint:
  stage: lint
  script:
    - flutter analyze

flutter_build_web:
  stage: build
  script:
    - flutter clean
    - flutter build web
  artifacts:
    paths:
      - counter_test/build/web/*