default:
  image: cirrusci/flutter:latest
  before_script:
    - cd counter_test
    - flutter pub get

stages:
  - test
  - lint
  - build
  - deploy

flutter_test:
  stage: test
  script:
    - flutter test
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

flutter_lint:
  stage: lint
  script:
    - flutter analyze
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

flutter_build_web:
  stage: build
  script:
    - flutter clean
    - flutter build web
  artifacts:
    paths:
      - counter_test/build/web/*
  rules:
    - if: $CI_COMMIT_BRANCH != "main"

pages:
  stage: deploy
  script:
    - flutter clean
    - flutter build web
    - cp -r build/web ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"